export const TRENDS_ARTICLE = "trends/TRENDS_ARTICLE";

export const TRENDS_USER_ARTICLE = "trends/TRENDS_USER_ARTICLE";

export const TRENDS_USER_NOT_LOGGED_ARTICLE =
  "trends/TRENDS_USER_NOT_LOGGED_ARTICLE";

export const TRENDS_ALL_ARTICLE = "trends/TRENDS_ALL_ARTICLE";

export const TRENDS_LIKE_ARTICLE = "trends/TRENDS_LIKE_ARTICLE";

export const TRENDS_DISLIKE_ARTICLE = "trends/TRENDS_DISLIKE_ARTICLE";

export const TRENDS_SET_CURRENT_RATING = "trends/TRENDS_SET_CURRENT_RATING";
