export const GET_SEARCH_RESULT_REQUESTED =
  "question/GET_SEARCH_RESULT_REQUESTED";
export const GET_SEARCH_RESULT_SUCCESSFUL =
  "question/GET_SEARCH_RESULT_SUCCESSFUL";
export const GET_SEARCH_RESULT_FAIL = "question/GET_SEARCH_RESULT_FAIL";
