export const GET_CMS_TEMPLATE_PREVIEW_REQUEST =
  "preview/CMS_TEMPLATE_PREVIEW_REQUEST";
export const GET_CMS_TEMPLATE_PREVIEW_SUCCESSFUL =
  "preview/CMS_TEMPLATE_PREVIEW_SUCCESSFUL";
export const GET_CMS_TEMPLATE_PREVIEW_FAIL =
  "preview/CMS_TEMPLATE_PREVIEW_FAIL";

export const GET_CONTENT_INFO_REQUEST = "profile/GET_CONTENT_INFO_REQUEST";
export const GET_CONTENT_INFO_SUCCESSFUL =
  "profile/GET_CONTENT_INFO_SUCCESSFUL";
export const GET_CONTENT_INFO_FAIL = "profile/GET_USER_CONTENT_FAIL";
