export const LOAD_CATEGORIES_REQUEST = 'tiles/LOAD_CATEGORIES_REQUEST';
export const LOAD_CATEGORIES = 'tiles/LOAD_CATEGORIES';
export const LOAD_CATEGORY_TILES_REQUEST = 'tiles/LOAD_CATEGORY_TILES_REQUEST';
export const LOAD_CATEGORY_TILES = 'tiles/LOAD_CATEGORY_TILES';

export const INSERT_CATEGORY_TILE_REQUEST = 'tiles/INSERT_CATEGORY_TILE_REQUEST';
export const INSERT_CATEGORY_TILE = 'tiles/INSERT_CATEGORY_TILE';
export const REMOVE_CATEGORY_TILE_REQUEST = 'tiles/REMOVE_CATEGORY_TILE_REQUEST';
export const REMOVE_CATEGORY_TILE = 'tiles/REMOVE_CATEGORY_TILE';
export const MOVE_CATEGORY_TILE_REQUEST = 'tiles/MOVE_CATEGORY_TILE_REQUEST';
export const MOVE_CATEGORY_TILE = 'tiles/MOVE_CATEGORY_TILE';
export const INSERT_NEW_CATEGORY_TILE_REQUEST = 'tiles/INSERT_NEW_CATEGORY_TILE_REQUEST';
export const INSERT_NEW_CATEGORY_TILE = 'tiles/INSERT_NEW_CATEGORY_TILE';
export const UPDATE_CATEGORY_TILE_REQUEST = 'tiles/UPDATE_CATEGORY_TILE_REQUEST';
export const UPDATE_CATEGORY_TILE = 'tiles/UPDATE_CATEGORY_TILE';
export const DELETE_CATEGORY_TILE_REQUEST = 'tiles/DELETE_CATEGORY_TILE_REQUEST';
export const DELETE_CATEGORY_TILE = 'tiles/DELETE_CATEGORY_TILE';

export const LOAD_UNUSED_TILES_REQUEST = 'tiles/LOAD_UNUSED_TILES_REQUEST';
export const LOAD_UNUSED_TILES = 'tiles/LOAD_UNUSED_TILES';

export const LOOKUP_CATEGORY_TILES_REQUEST = 'tiles/LOOKUP_CATEGORY_TILES_REQUEST';
export const LOOKUP_CATEGORY_TILES = 'tiles/LOOKUP_CATEGORY_TILES';