export const PATH_SIGNIN = "PATH_SIGIN";
export const PATH_SIGNOUT = "PATH_SIGNOUT";
export const PATH_FORGOT_PASSWORD = "PATH_FORGOT_PASSWORD";
export const PATH_RESET_PASSWORD_PASSWORD = "PATH_RESET_PASSWORD_PASSWORD";
export const PATH_VERIFY_PASSWORD = "PATH_VERIFY_PASSWORD";
export const UNAUTHORIZED = "UNAUTHORIZED";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const PATH_SIMPLE_REGISTER = "PATH_SIMPLE_REGISTER";
